### ISSUE TITLE
java.lang.NullPointerException on Pull/Merge of Origin verison

### ISSUE THREAD

**Issue by sgund** [lecture2go/plugins-sdk-6.2#233]
Thought ist was an error in my configuration but also happend on Fabian's machine. Functionality of l2g is not affected by the error. Thought it seems to cause eclipse crashes.

Occurs after 'merging' of repository, and occasionally other operations. First time occurance was after pio's comit in January.

Errors occurred during the build.
Errors running builder 'Theme CSS Builder' on project 'lecture2go-theme'.
java.lang.NullPointerException

**Comment by isturm** [comment]
known bug.
