### ISSUE TITLE
Upload Filename is split incorrectly if multiple dots are used

### ISSUE THREAD

**Issue by sgund** [lecture2go/plugins-sdk-6.2#241]
With a corrcectly replaced string,  uploadFilename and generationDate should look similar to this:

00.000_eLB-MIN_2016-02-22_15-25.mp4 => 2016-02-22_15-25 

Incorrect split leads to
00.000_elb_MIN_2016-02-22.mp4 => MIN_2016-02-22 

This causes Video Listing to crash for given producer. 
Example string causing error: "Thea & Jan_v.1.mp4"

Note: all changes to character parsing/replacement should be backward compatible and must be reflected in "set to open access" procedure as well, otherwise Filename on disk and filename in Databse could differ.

Workaround: Manually fix generationDate in Database by using uploadDate information
Must be formatted as YYYY-MM-DD_HH-MM

**Comment by isturm** [comment]
bug no longer occurs.
