### ISSUE TITLE
Select menu / lecture series management

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#325]
Drop down arrow out of alignment.

![bildschirmfoto 2016-05-12 um 14 28 23](https://cloud.githubusercontent.com/assets/8735970/15214541/e04ad7dc-184d-11e6-9fca-dd033401c1ef.png)

**Comment by FabianWillke** [comment]
@isturm Bei mir ist das in Firefox und Chrome nicht so. Ich glaube das wurde schon gelöst, oder ist es bie dir noch so?

**Comment by FabianWillke** [comment]
This only happens if the developer properties are turned off. Then "theme.css.fast.load" is true. This causes the background-position css property for the select elements to disapear, which is set in l2go.css (.aui select).
Why is this property lost with theme.css.fast.load?
