### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#535]
Entity "enter-password" not translated yet.

**Comment by danielksan81** [comment]
I expect that the entity must be added to the corresponding language files under https://github.com/lecture2go/plugins-sdk-6.2/tree/master/portlets/lecture2go-portlet/docroot/WEB-INF/src/content ?

**Comment by isturm** [comment]
you are right.

**Comment by danielksan81** [comment]
At least I can add the translation for german and add it to the default and en file.
Maybe you can add the hacktoberfest label to get then the other ones?

**Comment by isturm** [comment]
Where can i add this label. Is there any informaition about hacktoberfest? Thank you.

**Comment by danielksan81** [comment]
At the issue you should be able to add it.
Information you can find here: https://hacktoberfest.digitalocean.com/

**Comment by isturm** [comment]
i like github 👍
