### ISSUE TITLE
Searched and Found Lectureseries contain no videos if those don't match the query

### ISSUE THREAD

**Issue by mttsh** [lecture2go/plugins-sdk-6.2#581]
If a search query is matched on the lectureseries itself, all videos of this series should be marked as found as well -> the list should not be empty but contain all videos

**Comment by mttsh** [comment]
This problem seems to happen to older/migrated lectureseries only

**Comment by isturm** [comment]
video objects are not tagged in the tag cloud table as such one but as lescureseries.
