### ISSUE TITLE
MP4 upload not working in firefox

### ISSUE THREAD

**Issue by mttsh** [lecture2go/plugins-sdk-6.2#613]
Upload in firefox not working (system: mac os 10.11 / firefox 49.0 and 50.0 / no firefox plugin/addons)

error message:

"Kein akzeptables Format zum Hochladen!
Der erste Upload muss eine gültige Mp3 oder Mp4 Datei sein"

can this be reproduced on other machines?

**Comment by isturm** [comment]
FF 49.0.2 on MAC 10.10.5 works properly. Can you reproduce this behavior on your local host machine? Is there a proxy configured or any other browser properties are set?

**Comment by isturm** [comment]
can't reproduce!
