### ISSUE TITLE
Special characters (ä,ö,ü etc.) are not shown correctly on chapters

### ISSUE THREAD

**Issue by mttsh** [lecture2go/plugins-sdk-6.2#622]

**Comment by mttsh** [comment]
Example: https://lecture2go.uni-hamburg.de/l2go/-/get/v/10232 (first chapter at 0:00)

**Comment by mttsh** [comment]
Maybe a wrong character encoding in the VTT file?

**Comment by isturm** [comment]
Affects only files created before the lecture2go migration. Unfortunately the rest must be corrected manually. Encoding ist  UTF8.
