### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#684]
Spelling mistake 

Description:
Spelling mistake in the English translation file

Expected result:
edited-and-allowed-lecture-series=has edited and released the lecture series.

Actual result:
edited-and-allowed-lecture-series=has edited and releaset the lecture series.

**Comment by IndianKoder** [comment]
Hi..I will take it up!!

**Comment by JRIngram** [comment]
Happy to take this one!

**Comment by isturm** [comment]
Great Job JRIngram! Thank you!
