### ISSUE TITLE
institution filter ignores data set 

### ISSUE THREAD

**Issue by mttsh** [lecture2go/plugins-sdk-6.2#8]
catalogue site: after choosing a parentInstitution, all institutions from this parentInstitution are shown in the institution-filter and not only the ones which corresponds to the dataset.

![image](https://cloud.githubusercontent.com/assets/3171980/7960156/8dacb6d4-09fe-11e5-84f8-1cfc86490058.png)

**Comment by isturm** [comment]
pleace start pull request to merge this bug fix into lecture2go master branch

**Comment by mttsh** [comment]
fixed
