### ISSUE TITLE
guest role: open acces videos list failed to load 

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#9]
To reproduce this issue-> /l2gos/-/get/100/102/0/0/0

13:03:19,805 ERROR [http-bio-8080-exec-265][PortletRequestDispatcherImpl:115] org.apache.jasper.JasperException: An exception occurred processing JSP page /guest/videosList.jsp at line 99__96: 	pageContext.setAttribute("hasTermFiltered", hasTermFiltered);_97: 	pageContext.setAttribute("hasCategoryFiltered", hasCategoryFiltered);_98: 	pageContext.setAttribute("hasCreatorFiltered", hasCreatorFiltered);_99: 	pageContext.setAttribute("hasManyTerms", presentTerms.size() > maxTerms);_100: 	pageContext.setAttribute("hasManyCreators", presentCreators.size() > maxCreators);_101: 		_102: %>___Stacktrace: [Sanitized]
org.apache.jasper.JasperException: An exception occurred processing JSP page /guest/videosList.jsp at line 99__96: 	pageContext.setAttribute("hasTermFiltered", hasTermFiltered);_97: 	pageContext.setAttribute("hasCategoryFiltered", hasCategoryFiltered);_98: 	pageContext.setAttribute("hasCreatorFiltered", hasCreatorFiltered);_99: 	pageContext.setAttribute("hasManyTerms", presentTerms.size() > maxTerms);_100: 	pageContext.setAttribute("hasManyCreators", presentCreators.size() > maxCreators);_101: 		_102: %>___Stacktrace: [Sanitized]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:568)

**Comment by mttsh** [comment]
depends on #8
