### ISSUE TITLE
Producer Ids not correctly transfered

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#90]
The Producer Ids are not correctly transfered after migration script for the table lg_producer_lectureseries has run. It seems, that the new generated user ids are not mapped on the producer ids from this table.

**Comment by sgund** [comment]
Producer wird soweit korrekt auf die neuen UserIds gemappt
producer = ProducerLocalServiceUtil.getProducer(UserIDMapper.getNewUserId(legacyProducer.getId(), companyId));.

Das neue UserId Mapping müsste dann auch in producerLecturseriesMapper rein anstelle der ursprünglichen ProducerId
producerLectureseries.setProducerId(legacyProducerLectureseries.getProducerId());

**Comment by isturm** [comment]
Ja, genau. Danke für den Hinweis.

**Comment by EikeSalow** [comment]
ok ich habs commited

**Comment by EikeSalow** [comment]
und gepushend in meinen branch

**Comment by isturm** [comment]
thanks.
